#!/usr/bin/env bash
#
# SPDX-License-Identifier: AGPL-3.0-or-later

_bin="$( \
  dirname \
    "$( \
      command \
        -v \
	  "env")")"
_lib="${_bin}/../lib"
source \
  "${_lib}/libcrash-bash/crash-bash"

# shellcheck disable=SC2034
_global_variables() {
  target_command=""
  target_display=""
  target_key=""
  target_value=""
  color=""
  quiet=""
}

_requirements() {
  local \
    _app
  _check_cmd \
    'display-status' \
    'android-utils'
  _check_cmd \
    "su" \
    "tsu"
}

_get_conf_dir_path() {
  local \
    _dir
  _dir="${HOME}/.config/$( \
    _get \
      "app" \
      "name")"
  echo \
    "${_dir}"
}

_displayctl() {
  local \
    _command="${1}" \
    _cmd \
    _args=() \
    _app \
    _db
  if [[ "${_command}" == "get" ]]; then
    _cmd="_${_command}_display_key_value"
    _args+=(
      "$( \
        _get \
          "target" \
          "display")"
      "$( \
        _get \
          "target" \
          "key")"
      )
  elif [[ "${_command}" == "set" ]]; then
    _cmd="_${_command}_display_key_value"
    _args+=(
      "$( \
        _get \
          "target" \
          "display")"
      "$( \
        _get \
          "target" \
          "key")"
      "$( \
        _get \
          "target" \
          "value")"
    )
  fi
  "${_cmd}" \
    "${_args[@]}"
}

# Set key for a display
_set_display_key_value() {
  local \
    _display="${1}" \
    _key="${2}" \
    _value="${3}" \
    _cmd=()
  _msg_info \
    "Setting value ${_value} for key ${_key} of display '${_display}'"
  if [[ "${_key}" == "status" ]]; then
    if [[ "$(display-status)" != "${_value}" ]]; then
      _cmd=(
        input
          keyevent
          KEYCODE_POWER
      )
      _msg_info \
        "Running ${_cmd[*]}"
      su \
        -c \
        "${_cmd[*]}"
    fi
  fi
}

# Get display settings key
# $1: target settings key
_get_display_key_value() {
  local \
    _display="${1}" \
    _key="${2}" \
    _msg=() \
    _account
  if [[ "${_key}" == "status" ]]; then
    display-status
  fi
}

_set_overrides() {
  _set_override \
    "target" \
    "display" \
    "default"
  if [[ -v override_quiet ]]; then
    quiet="${override_quiet}"
  elif [[ -z "${quiet}" ]]; then
    quiet="y"
  fi
  if [[ -v override_color ]]; then
    color="${override_color}"
  elif [[ -z "${color}" ]]; then
    color="n"
  fi
}

# Show help usage, with an exit status.
# $1: exit status number.
_usage() {
  local \
    _usage_text
  IFS='' \
    read \
      -r \
      -d '' \
      _usage_text << \
        ENDUSAGETEXT || true
Manage displays
usage:
  $(_get "app" "name")
    [options]
    <command>
    <key>
    (<value>)
  commands:
     get                  Get configuration value
       <key>
     set                  Set configuration value
       <key>
       <value>
  keys:
    status                Can be 'off' or 'on'.
  options:
     -d <display>         Display to select.
                          Default: $(_get "target" "display")
     -h                   This message.
     -c                   Enable color output
     -v                   Enable verbose output
ENDUSAGETEXT
  _printf \
    '%s\n' \
    "${_usage_text}"
  exit \
    "${1}"
}

_display_flags() {
  local \
    _flags=(
      "${1}"
    ) \
    _flag
  for _flag \
    in "${_flags[@]}"; do
  _msg_info \
    "                             ${_flag}"
  done
}

# Shows configuration options.
_show_config() {
  local \
    _get_date
  TZ=UTC \
    printf \
      -v _get_date \
      '%(%FT%R%z)T' \
      "${SOURCE_DATE_EPOCH}"
  _msg_info "${app_name} configuration"
  _msg_info "           Operation date:   $(_get "_get" "date")"
  _msg_info "           Target command:   $(_get "target" "command")"
  _msg_info "           Target display:   $(_get "target" "display")"
  _msg_info "               Target key:   $(_get "target" "key")"
  _msg_info "             Target value:   $(_get "target" "value")"
}

_globals
_global_variables
_requirements
_config_user_init \
  "$(_get \
       "app" \
       "name")"
# shellcheck disable=SC2034
while \
  getopts \
    'a:p:k:cvh?' \
    arg; do
  case \
    "${arg}" in
    a) override_target_address="${OPTARG}" ;;
    p) override_target_port="${OPTARG}" ;;
    k) override_target_password="${OPTARG}" ;;
    c) override_color="y" ;;
    v) override_quiet="n" ;;
    h|?) _set_overrides && \
         _usage \
           0 ;;
    *)
    _msg_error \
      "Invalid argument '${arg}'" \
      0
    _usage \
      1
    ;;
  esac
done
shift \
  $(( \
    OPTIND - 1 \
  ))
if (( $# < 1 )); then
  _msg_error \
    "no command given" \
    0
  _set_overrides
  _usage \
    1
fi
_set \
  "target" \
  "command" \
  "${1}"
if (( 1 < $# )); then
  _set \
    "target" \
    "key" \
    "${2}"
fi
if (( 2 < $# )); then
  _set \
    "target" \
    "value" \
    "${3}"
fi
_set_overrides
_config_user_init \
  "$( \
    _get \
      "app" \
      "name")"
_show_config
app_opts=(
  "$( \
    _get \
      "target" \
      "command")"
)
_displayctl \
  "${app_opts[@]}"

# vim:set sw=2 sts=-1 et:
